# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EcoNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EcoNews
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'SwiftSoup'
end
